services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pofolitdb'
      - 'MYSQL_PASSWORD=sa'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=han'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    restart: always
