spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pofolitdb?useSSL=false/serverTimezone=Asia/Seoul&characterEncoding=UTF-8/
    username: root
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  jwt:
    secret: "popopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercver"
    expiration: 3600