uri:
  auth:
    base: "http://localhost:3000"
    signup: "http://localhost:3000/signup"
server:
  port: 8080
logging:
  level:
    root: INFO
    org.hibernate.orm: INFO
spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/pofolitdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sa}
  jpa:
    hibernate:
      ddl-auto: update #
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db-migration/
    baseline-on-migrate: true
    baseline-version: 1
    sql-migration-suffixes: .sql
    encoding: UTF-8
    clean-disabled: false
  jwt:
    secret: ${JWT_SECRET:popopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercverpopopopopopfolitsercver}
    expiration: ${JWT_EXP:300}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - account_email
              - profile_nickname
              - profile_image
            client-name: Kakao
        provider:
          kakao:
            # OIDC 표준
            issuer-uri: https://kauth.kakao.com